# Generated by Django 3.0.4 on 2020-03-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1)),
                ('period', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('friday_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri1', to='index.MyClass')),
                ('friday_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri2', to='index.MyClass')),
                ('friday_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri3', to='index.MyClass')),
                ('friday_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri4', to='index.MyClass')),
                ('friday_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri5', to='index.MyClass')),
                ('monday_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon1', to='index.MyClass')),
                ('monday_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon2', to='index.MyClass')),
                ('monday_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon3', to='index.MyClass')),
                ('monday_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon4', to='index.MyClass')),
                ('monday_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon5', to='index.MyClass')),
                ('thursday_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu1', to='index.MyClass')),
                ('thursday_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu2', to='index.MyClass')),
                ('thursday_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu3', to='index.MyClass')),
                ('thursday_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu4', to='index.MyClass')),
                ('thursday_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu5', to='index.MyClass')),
                ('tuesday_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue1', to='index.MyClass')),
                ('tuesday_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue2', to='index.MyClass')),
                ('tuesday_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue3', to='index.MyClass')),
                ('tuesday_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue4', to='index.MyClass')),
                ('tuesday_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue5', to='index.MyClass')),
                ('wednesday_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed1', to='index.MyClass')),
                ('wednesday_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed2', to='index.MyClass')),
                ('wednesday_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed3', to='index.MyClass')),
                ('wednesday_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed4', to='index.MyClass')),
                ('wednesday_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed5', to='index.MyClass')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('my_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.MyClass')),
            ],
        ),
    ]
