# Generated by Django 3.0.4 on 2020-03-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='day',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='period',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
