# Generated by Django 3.0.4 on 2020-03-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200330_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
