# Generated by Django 3.0.4 on 2020-03-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200330_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
