# Generated by Django 3.0.4 on 2020-04-01 07:17

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200401_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='picture',
            new_name='picture1',
        ),
        migrations.AddField(
            model_name='information',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.user_portfolio_directory_path),
        ),
        migrations.AddField(
            model_name='information',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.user_portfolio_directory_path),
        ),
        migrations.AddField(
            model_name='information',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.user_portfolio_directory_path),
        ),
        migrations.AddField(
            model_name='information',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.user_portfolio_directory_path),
        ),
    ]
