# Generated by Django 3.0.4 on 2020-04-01 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200401_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
